name: trustmebro-back

services:
  trustmebro-back:
    image: trustmebro-back:v0.3.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - REDIS_URL=redis
      - APP_PORT=8080
      - APP_URL=http://localhost
  
  redis:
    image: redis
    ports:
      - 6379:6379

  

    